name: Update Dependencies
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Update dependencies
        run: |
          bunx update
          bun install

      - name: Commit updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No updates avalable"
          else
            git commit -m "chore(deps): bump dependencies"
            git push
          fi
